version: '3.1'

services:
  db:
    build: .
    container_name: conexblog-db
    restart: 'always'
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - C:\dev\conex-blog\.docker\dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=conexblog
